from django.urls import path

from .views import (
    account_change_request,
    account_change_request_approve,
    account_change_request_list,
    account_change_request_reject,
    account_create,
    account_list,
    api_finance_refresh,
    api_finance_stats,
    bank_expense_create,
    cash_expense_create,
    cash_income_create,
    category_create,
    category_list,
    finance_guide,
    home,
    htmx_currency_detail,
    htmx_finance_accounts,
    htmx_finance_expenses,
    htmx_finance_income,
    htmx_report_summary,
    htmx_transaction_list,
    import_confirm,
    import_list,
    import_new,
    import_preview,
    online_donation_income_create,
    receipt_download,
    report_dashboard,
    transfer_create,
    transaction_approve,
    transaction_edit,
    transaction_list,
    transaction_reject,
)
from .views_users import pending_access, user_create, user_edit, user_list

urlpatterns = [
    path("", home, name="home"),
    path("categories/", category_list, name="category_list"),
    path("categories/create/", category_create, name="category_create"),
    path("accounts/", account_list, name="account_list"),
    path("accounts/create/", account_create, name="account_create"),
    path(
        "accounts/<int:pk>/change-request/",
        account_change_request,
        name="account_change_request",
    ),
    path(
        "account-change-requests/<int:pk>/approve/",
        account_change_request_approve,
        name="account_change_request_approve",
    ),
    path(
        "account-change-requests/",
        account_change_request_list,
        name="account_change_request_list",
    ),
    path(
        "account-change-requests/<int:pk>/reject/",
        account_change_request_reject,
        name="account_change_request_reject",
    ),
    path("transactions/", transaction_list, name="transaction_list"),
    path("transactions/<int:pk>/edit/", transaction_edit, name="transaction_edit"),
    path("transactions/<int:pk>/approve/", transaction_approve, name="transaction_approve"),
    path("transactions/<int:pk>/reject/", transaction_reject, name="transaction_reject"),
    path(
        "cash-incomes/create/",
        cash_income_create,
        name="cash_income_create",
    ),
    path(
        "cash-expenses/create/",
        cash_expense_create,
        name="cash_expense_create",
    ),
    path(
        "bank-expenses/create/",
        bank_expense_create,
        name="bank_expense_create",
    ),
    path(
        "online-donations/create/",
        online_donation_income_create,
        name="online_donation_income_create",
    ),
    path(
        "transfers/create/",
        transfer_create,
        name="transfer_create",
    ),
    path(
        "receipts/<int:pk>/download/",
        receipt_download,
        name="receipt_download",
    ),
    path(
        "imports/pending/",
        import_list,
        name="import_list",
    ),
    path(
        "imports/new/",
        import_new,
        name="import_new",
    ),
    path(
        "imports/<int:pk>/preview/",
        import_preview,
        name="import_preview",
    ),
    path(
        "imports/<int:pk>/confirm/",
        import_confirm,
        name="import_confirm",
    ),
    path("reports/", report_dashboard, name="report_dashboard"),
    path("finance-guide/", finance_guide, name="finance_guide"),
    path("htmx/finance/income/", htmx_finance_income, name="htmx_finance_income"),
    path("htmx/finance/expenses/", htmx_finance_expenses, name="htmx_finance_expenses"),
    path("htmx/finance/accounts/", htmx_finance_accounts, name="htmx_finance_accounts"),
    path(
        "htmx/currency/<str:currency>/",
        htmx_currency_detail,
        name="htmx_currency_detail",
    ),
    path("htmx/transactions/", htmx_transaction_list, name="htmx_transaction_list"),
    path("htmx/reports/", htmx_report_summary, name="htmx_report_summary"),
    path("api/finance-stats/", api_finance_stats, name="api_finance_stats"),
    path("api/finance-stats/refresh/", api_finance_refresh, name="api_finance_refresh"),
    path("pending/", pending_access, name="pending_access"),
    path("users/", user_list, name="user_list"),
    path("users/create/", user_create, name="user_create"),
    path("users/<int:pk>/edit/", user_edit, name="user_edit"),
]
