# Generated by Django 5.2.14 on 2026-06-03 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onikisepet', '0004_transaction'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='payee',
            field=models.CharField(blank=True, max_length=150),
        ),
    ]
