# Generated by Django 6.0.2 on 2026-06-20 00:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onikisepet', '0007_auditlog'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='approval_status',
            field=models.CharField(
                choices=[
                    ('pending', 'Onay bekliyor'),
                    ('approved', 'Onaylandı'),
                    ('rejected', 'Reddedildi'),
                ],
                default='approved',
                max_length=10,
            ),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='transaction',
            name='approved_by',
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name='approved_transactions',
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
