# Generated by Django 5.2.14 on 2026-09-10 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('onikisepet', '0009_transaction_is_void_transaction_void_reason_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['category_type', 'name']},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100),
        ),
        migrations.AddConstraint(
            model_name='category',
            constraint=models.UniqueConstraint(fields=('name', 'category_type'), name='unique_category_name_per_type'),
        ),
    ]
