# Generated by Django 5.2.14 on 2026-06-20 14:00

from pathlib import Path

from django.db import migrations, models


def populate_receipt_file_type(apps, schema_editor):
    Receipt = apps.get_model("onikisepet", "Receipt")
    extension_map = {
        ".pdf": "pdf",
        ".jpg": "jpg",
        ".jpeg": "jpg",
        ".png": "png",
    }

    for receipt in Receipt.objects.all():
        extension = Path(receipt.original_filename).suffix.lower()
        receipt.file_type = extension_map.get(extension, "jpg")
        receipt.save(update_fields=["file_type"])


class Migration(migrations.Migration):

    dependencies = [
        ("onikisepet", "0009_profile"),
    ]

    operations = [
        migrations.AddField(
            model_name="receipt",
            name="file_type",
            field=models.CharField(
                choices=[("pdf", "PDF"), ("jpg", "JPG"), ("png", "PNG")],
                default="jpg",
                max_length=10,
            ),
            preserve_default=False,
        ),
        migrations.RunPython(
            populate_receipt_file_type,
            migrations.RunPython.noop,
        ),
    ]
